// wadoversteken.nl — dieptestaat en getijkarakteristiek per wantij/geul.
//
// Bron: door de gebruiker aangeleverde "Wadvaarders_dieptestaat.xlsx"
// (peildatum van de dataset zelf: zie elke geul zijn eigen `peildatum`;
// de dieptes zijn dus geen live meting maar een periodieke momentopname).
// Aangevuld met de achtergrondtekst uit "Wantijen Waddenzee.docx" (de zeven
// hoofdwantijen en De Gouden Regel) — zie de .wantijen-sectie in index.html.
//
// Elke geul/wantij heeft:
// - diepteNAP_dm / diepteALAT_dm: minst gelode diepte (de ondiepste bult),
//   in decimeter, t.o.v. NAP resp. ALAT (Laagste Astronomische Getij).
// - alatNapVerschil_dm: hoeveel ALAT onder NAP ligt op deze plek (dm),
//   nodig om diepteNAP en het getij (dat in NAP-achtige termen werkt via
//   RWS) op één lijn te krijgen met diepteALAT.
// - spring / dood: { hwALAT_dm, verval_dm } — de karakteristieke hoogte
//   van hoogwater (t.o.v. ALAT) en het verval (HW − LW) bij springtij resp.
//   doodtij op deze geul, in dm. Invoer voor de 1/12e-regel (zie wantij.js).
// - referentiepunt: welk bestaand RWS-referentiepunt (zie REFERENCE_POINTS
//   in api/getij.js en REFERENCE_LABELS in routes-data.js) het dichtst bij
//   deze geul ligt en dus de HW/LW-tíjden levert. `null` = nog geen geschikt
//   referentiepunt in de site (zie WANTIJ_REFERENTIEPUNT_ONTBREEKT hieronder).
// - zekerheid: 'zeker' als de koppeling direct is bevestigd (via een
//   bestaande route in routes-data.js, of expliciet genoemd in het
//   wantijen-document), 'schatting' als het een educated guess is op basis
//   van geografische ligging/naamgeving — DEZE VERDIENEN EEN CONTROLE DOOR
//   IEMAND MET VAARKENNIS VAN HET GEBIED voordat dit als scherp advies
//   gepresenteerd wordt, niet alleen als indicatie.
// - toelichting: korte onderbouwing van de keuze.

const WANTIJ_REFERENTIEPUNT_ONTBREEKT =
  'Voor deze geul is nog geen RWS-referentiepunt gekoppeld (Eems-Dollard-gebied, ' +
  'nog niet elders op de site gebruikt). Zoek het juiste RWS-locatiecode op via ' +
  'METADATASERVICES/OphalenCatalogus (Groepering GETETBRKD2) en vul het aan in ' +
  'REFERENCE_POINTS (api/getij.js), REFERENCE_LABELS/REFERENCE_COORDS ' +
  '(routes-data.js) én het `referentiepunt`-veld hieronder.'

const WANTIJEN = [
  {
    id: "ballumerbocht",
    naam: "Ballumerbocht",
    regio: "oostelijk", // 'westelijk' | 'oostelijk'
    betonning: "BB10",
    diepteNAP_dm: 25,
    diepteALAT_dm: 8,
    alatNapVerschil_dm: 17,
    peildatum: "15-10-2025",
    referentiepunt: "ameland",
    zekerheid: "zeker",
    toelichting: "Ballum is een dorp op Ameland.",
    spring: { hwALAT_dm: 30, verval_dm: 28 },
    dood: { hwALAT_dm: 26, verval_dm: 19 },
  },
  {
    id: "binnen-breesem",
    naam: "Binnen Breesem",
    regio: "westelijk", // 'westelijk' | 'oostelijk'
    betonning: "BR24 <--> FD-BR",
    diepteNAP_dm: 6,
    diepteALAT_dm: -6,
    alatNapVerschil_dm: 12,
    peildatum: "11-02-2026",
    referentiepunt: "harlingen",
    zekerheid: "schatting",
    toelichting: "Op de route Den Helder → Kornwerderzand/Harlingen, vlak voor Harlingen.",
    spring: { hwALAT_dm: 20, verval_dm: 17 },
    dood: { hwALAT_dm: 18, verval_dm: 14 },
  },
  {
    id: "blauwe-balg",
    naam: "Blauwe Balg",
    regio: "westelijk", // 'westelijk' | 'oostelijk'
    betonning: "BB1 <--> BB3",
    diepteNAP_dm: 35,
    diepteALAT_dm: 18,
    alatNapVerschil_dm: 17,
    peildatum: "18-03-2026",
    referentiepunt: "vlieland",
    zekerheid: "schatting",
    toelichting: "Tussen Vlieland en Terschelling.",
    spring: { hwALAT_dm: 29, verval_dm: 26 },
    dood: { hwALAT_dm: 25, verval_dm: 18 },
  },
  {
    id: "boontjes",
    naam: "Boontjes",
    regio: "westelijk", // 'westelijk' | 'oostelijk'
    betonning: "BO25 <--> BO27",
    diepteNAP_dm: 34,
    diepteALAT_dm: 21,
    alatNapVerschil_dm: 13,
    peildatum: "22-06-2026",
    referentiepunt: "harlingen",
    zekerheid: "zeker",
    toelichting: "Komt direct overeen met de bestaande route Harlingen – Oudeschild via Boontjes.",
    spring: { hwALAT_dm: 24, verval_dm: 21 },
    dood: { hwALAT_dm: 21, verval_dm: 16 },
  },
  {
    id: "boschgat-bij-ameland",
    naam: "Boschgat bij Ameland",
    regio: "westelijk", // 'westelijk' | 'oostelijk'
    betonning: "Dieptes onbetrouwbaar. Betonning opgenomen",
    diepteNAP_dm: 1,
    diepteALAT_dm: -15,
    alatNapVerschil_dm: 16,
    peildatum: "17-12-2025",
    referentiepunt: "ameland",
    zekerheid: "zeker",
    toelichting: "Naam verwijst direct naar Ameland.",
    spring: { hwALAT_dm: 27, verval_dm: 25 },
    dood: { hwALAT_dm: 23, verval_dm: 17 },
  },
  {
    id: "boschwad",
    naam: "Boschwad",
    regio: "oostelijk", // 'westelijk' | 'oostelijk'
    betonning: "BW8 <--> S2",
    diepteNAP_dm: 1,
    diepteALAT_dm: -17,
    alatNapVerschil_dm: 18,
    peildatum: "03-04-2026",
    referentiepunt: "ameland",
    zekerheid: "zeker",
    toelichting: "Doc: route (BW) vanaf Ameland richting Lauwersoog.",
    spring: { hwALAT_dm: 28, verval_dm: 25 },
    dood: { hwALAT_dm: 25, verval_dm: 19 },
  },
  {
    id: "dollard",
    naam: "Dollard",
    regio: "oostelijk", // 'westelijk' | 'oostelijk'
    betonning: "D71 <--> D73",
    diepteNAP_dm: 14,
    diepteALAT_dm: -12,
    alatNapVerschil_dm: 26,
    peildatum: "22-04-2026",
    referentiepunt: null,
    zekerheid: "ontbreekt",
    toelichting: "Bij de Eems-Dollard/Delfzijl; er is nog geen RWS-referentiepunt voor dit gebied in de site.",
    spring: { hwALAT_dm: 43, verval_dm: 35 },
    dood: { hwALAT_dm: 39, verval_dm: 29 },
  },
  {
    id: "eilanderbalg",
    naam: "Eilanderbalg",
    regio: "oostelijk", // 'westelijk' | 'oostelijk'
    betonning: "EB10",
    diepteNAP_dm: 11,
    diepteALAT_dm: -7,
    alatNapVerschil_dm: 18,
    peildatum: "02-04-2026",
    referentiepunt: "schiermonnikoog",
    zekerheid: "zeker",
    toelichting: "Doc: wantij van Schiermonnikoog is de Eilanderbalg.",
    spring: { hwALAT_dm: 28, verval_dm: 25 },
    dood: { hwALAT_dm: 25, verval_dm: 18 },
  },
  {
    id: "eierlandsche-gat-dam",
    naam: "Eierlandsche Gat-Dam",
    regio: "westelijk", // 'westelijk' | 'oostelijk'
    betonning: "ED-B <--> RG1",
    diepteNAP_dm: 36,
    diepteALAT_dm: 22,
    alatNapVerschil_dm: 14,
    peildatum: "24-03-2022",
    referentiepunt: "texel",
    zekerheid: "schatting",
    toelichting: "Eierlandse Gat, bij de noordpunt van Texel.",
    spring: { hwALAT_dm: 24, verval_dm: 22 },
    dood: { hwALAT_dm: 21, verval_dm: 14 },
  },
  {
    id: "fransche-gaatje",
    naam: "Fransche Gaatje",
    regio: "westelijk", // 'westelijk' | 'oostelijk'
    betonning: "FG1 <--> FG3",
    diepteNAP_dm: 9,
    diepteALAT_dm: -6,
    alatNapVerschil_dm: 15,
    peildatum: "02-03-2026",
    referentiepunt: "texel",
    zekerheid: "schatting",
    toelichting: "Ten noorden van Texel.",
    spring: { hwALAT_dm: 24, verval_dm: 21 },
    dood: { hwALAT_dm: 21, verval_dm: 15 },
  },
  {
    id: "holwerderbalg",
    naam: "Holwerderbalg",
    regio: "oostelijk", // 'westelijk' | 'oostelijk'
    betonning: "HB11A <--> HB 13",
    diepteNAP_dm: 5,
    diepteALAT_dm: -13,
    alatNapVerschil_dm: 18,
    peildatum: "10-04-2026",
    referentiepunt: "ameland",
    zekerheid: "zeker",
    toelichting: "Doc: Ameland (Pinkegat/Holwerderbalg).",
    spring: { hwALAT_dm: 29, verval_dm: 26 },
    dood: { hwALAT_dm: 26, verval_dm: 19 },
  },
  {
    id: "frieschewad",
    naam: "Frieschewad",
    regio: "oostelijk", // 'westelijk' | 'oostelijk'
    betonning: "FW10 <--> HB1 en FW5, drempel",
    diepteNAP_dm: 12,
    diepteALAT_dm: -6,
    alatNapVerschil_dm: 18,
    peildatum: "31-03-2026",
    referentiepunt: "ameland",
    zekerheid: "zeker",
    toelichting: "Doc: wantij van Ameland via het Friesche Wad.",
    spring: { hwALAT_dm: 29, verval_dm: 26 },
    dood: { hwALAT_dm: 26, verval_dm: 19 },
  },
  {
    id: "geul-van-brakzand",
    naam: "Geul van Brakzand",
    regio: "oostelijk", // 'westelijk' | 'oostelijk'
    betonning: "BZ7 <--> BZ9",
    diepteNAP_dm: 4,
    diepteALAT_dm: -14,
    alatNapVerschil_dm: 18,
    peildatum: "17-04-2026",
    referentiepunt: "schiermonnikoog",
    zekerheid: "zeker",
    toelichting: "Doc noemt Brakzand bij Schiermonnikoog.",
    spring: { hwALAT_dm: 28, verval_dm: 26 },
    dood: { hwALAT_dm: 25, verval_dm: 19 },
  },
  {
    id: "gat-van-schiermonnikoog",
    naam: "Gat van Schiermonnikoog",
    regio: "oostelijk", // 'westelijk' | 'oostelijk'
    betonning: "GVS4 tot GVS6",
    diepteNAP_dm: 54,
    diepteALAT_dm: 36,
    alatNapVerschil_dm: 18,
    peildatum: "18-05-2026",
    referentiepunt: "schiermonnikoog",
    zekerheid: "zeker",
    toelichting: "Naam verwijst direct naar Schiermonnikoog.",
    spring: { hwALAT_dm: 28, verval_dm: 26 },
    dood: { hwALAT_dm: 25, verval_dm: 19 },
  },
  {
    id: "glinder",
    naam: "Glinder",
    regio: "oostelijk", // 'westelijk' | 'oostelijk'
    betonning: "GL7 <--> GVS1-GL9",
    diepteNAP_dm: 35,
    diepteALAT_dm: 17,
    alatNapVerschil_dm: 18,
    peildatum: "18-05-2026",
    referentiepunt: "schiermonnikoog",
    zekerheid: "schatting",
    toelichting: "Vaargeul bij Schiermonnikoog/Lauwersoog.",
    spring: { hwALAT_dm: 30, verval_dm: 28 },
    dood: { hwALAT_dm: 26, verval_dm: 20 },
  },
  {
    id: "groningerbalg",
    naam: "Groningerbalg",
    regio: "oostelijk", // 'westelijk' | 'oostelijk'
    betonning: "GB12 <--> GB-LW",
    diepteNAP_dm: 8,
    diepteALAT_dm: -10,
    alatNapVerschil_dm: 18,
    peildatum: "09-04-2026",
    referentiepunt: "lauwersoog",
    zekerheid: "schatting",
    toelichting: "Oostelijker, richting Lauwersoog.",
    spring: { hwALAT_dm: 28, verval_dm: 26 },
    dood: { hwALAT_dm: 25, verval_dm: 19 },
  },
  {
    id: "groote-siege-rode-zijde",
    naam: "Groote Siege (rode zijde)",
    regio: "oostelijk", // 'westelijk' | 'oostelijk'
    betonning: "GS12 <--> GS14, rand vaarwater",
    diepteNAP_dm: 35,
    diepteALAT_dm: 18,
    alatNapVerschil_dm: 17,
    peildatum: "18-05-2026",
    referentiepunt: "schiermonnikoog",
    zekerheid: "schatting",
    toelichting: "Bij Schiermonnikoog.",
    spring: { hwALAT_dm: 29, verval_dm: 28 },
    dood: { hwALAT_dm: 26, verval_dm: 20 },
  },
  {
    id: "inschot",
    naam: "Inschot",
    regio: "westelijk", // 'westelijk' | 'oostelijk'
    betonning: "IN17",
    diepteNAP_dm: 28,
    diepteALAT_dm: 15,
    alatNapVerschil_dm: 13,
    peildatum: "17-05-2026",
    referentiepunt: "vlieland",
    zekerheid: "zeker",
    toelichting: "Komt direct overeen met de bestaande route Vlieland – Oudeschild via Inschot.",
    spring: { hwALAT_dm: 22, verval_dm: 19 },
    dood: { hwALAT_dm: 20, verval_dm: 16 },
  },
  {
    id: "kimstergat",
    naam: "Kimstergat",
    regio: "westelijk", // 'westelijk' | 'oostelijk'
    betonning: "K32 <--> K36",
    diepteNAP_dm: 1,
    diepteALAT_dm: -16,
    alatNapVerschil_dm: 17,
    peildatum: "24-02-2026",
    referentiepunt: "harlingen",
    zekerheid: "zeker",
    toelichting: "Doc: ‘direct ten oosten van Harlingen’; komt ook voor in bestaande routes.",
    spring: { hwALAT_dm: 25, verval_dm: 25 },
    dood: { hwALAT_dm: 21, verval_dm: 18 },
  },
  {
    id: "kikkertgat",
    naam: "Kikkertgat",
    regio: "oostelijk", // 'westelijk' | 'oostelijk'
    betonning: "KG12",
    diepteNAP_dm: 13,
    diepteALAT_dm: -4,
    alatNapVerschil_dm: 17,
    peildatum: "25-03-2026",
    referentiepunt: "ameland",
    zekerheid: "schatting",
    toelichting: "Tussen Ameland en Terschelling.",
    spring: { hwALAT_dm: 26, verval_dm: 26 },
    dood: { hwALAT_dm: 23, verval_dm: 18 },
  },
  {
    id: "kromme-balg",
    naam: "Kromme Balg",
    regio: "westelijk", // 'westelijk' | 'oostelijk'
    betonning: "KB1-VH18 tot KB3",
    diepteNAP_dm: 15,
    diepteALAT_dm: -2,
    alatNapVerschil_dm: 17,
    peildatum: "24-03-2026",
    referentiepunt: "vlieland",
    zekerheid: "zeker",
    toelichting: "Doc: wantij van Vlieland via Kromme Balg.",
    spring: { hwALAT_dm: 26, verval_dm: 23 },
    dood: { hwALAT_dm: 23, verval_dm: 17 },
  },
  {
    id: "lutjewad-hornhuizerwad",
    naam: "Lutjewad (Hornhuizerwad)",
    regio: "oostelijk", // 'westelijk' | 'oostelijk'
    betonning: "LW20 <-->LW22",
    diepteNAP_dm: 8,
    diepteALAT_dm: -10,
    alatNapVerschil_dm: 18,
    peildatum: "09-04-2026",
    referentiepunt: "lauwersoog",
    zekerheid: "schatting",
    toelichting: "Bij de Groninger kust, richting Lauwersoog.",
    spring: { hwALAT_dm: 29, verval_dm: 25 },
    dood: { hwALAT_dm: 26, verval_dm: 19 },
  },
  {
    id: "molengat-onder-ameland",
    naam: "Molengat onder Ameland",
    regio: "westelijk", // 'westelijk' | 'oostelijk'
    betonning: "MG6 <--> MG8",
    diepteNAP_dm: 24,
    diepteALAT_dm: 7,
    alatNapVerschil_dm: 17,
    peildatum: "25-03-2026",
    referentiepunt: "ameland",
    zekerheid: "zeker",
    toelichting: "Naam verwijst direct naar Ameland (niet hetzelfde Molengat als bij Den Helder/Texel).",
    spring: { hwALAT_dm: 30, verval_dm: 28 },
    dood: { hwALAT_dm: 26, verval_dm: 19 },
  },
  {
    id: "molenrak",
    naam: "Molenrak",
    regio: "westelijk", // 'westelijk' | 'oostelijk'
    betonning: "MR2",
    diepteNAP_dm: 11,
    diepteALAT_dm: -2,
    alatNapVerschil_dm: 13,
    peildatum: "23-02-2026",
    referentiepunt: "texel",
    zekerheid: "schatting",
    toelichting: "Bij Oudeschild/Marsdiep, Texel.",
    spring: { hwALAT_dm: 24, verval_dm: 20 },
    dood: { hwALAT_dm: 21, verval_dm: 16 },
  },
  {
    id: "oort",
    naam: "Oort",
    regio: "oostelijk", // 'westelijk' | 'oostelijk'
    betonning: "O19 <--> LW2",
    diepteNAP_dm: 3.5,
    diepteALAT_dm: -14.5,
    alatNapVerschil_dm: 18,
    peildatum: "09-04-2026",
    referentiepunt: "lauwersoog",
    zekerheid: "schatting",
    toelichting: "Bij Lauwersoog.",
    spring: { hwALAT_dm: 28, verval_dm: 25 },
    dood: { hwALAT_dm: 25, verval_dm: 19 },
  },
  {
    id: "oosterom-bij-o20",
    naam: "Oosterom bij O20",
    regio: "westelijk", // 'westelijk' | 'oostelijk'
    betonning: "O18 <--> O22",
    diepteNAP_dm: 13,
    diepteALAT_dm: -2,
    alatNapVerschil_dm: 15,
    peildatum: "02-03-2026",
    referentiepunt: "terschelling",
    zekerheid: "zeker",
    toelichting: "Doc: wantij van Terschelling is Oosterom.",
    spring: { hwALAT_dm: 27, verval_dm: 24 },
    dood: { hwALAT_dm: 24, verval_dm: 17 },
  },
  {
    id: "oosterom-wantij",
    naam: "Oosterom (wantij)",
    regio: "westelijk", // 'westelijk' | 'oostelijk'
    betonning: "O48 <--> O54",
    diepteNAP_dm: 10,
    diepteALAT_dm: -5,
    alatNapVerschil_dm: 15,
    peildatum: "02-03-2026",
    referentiepunt: "terschelling",
    zekerheid: "zeker",
    toelichting: "Doc: wantij van Terschelling is Oosterom.",
    spring: { hwALAT_dm: 27, verval_dm: 24 },
    dood: { hwALAT_dm: 24, verval_dm: 17 },
  },
  {
    id: "paesensrede",
    naam: "Paesensrede",
    regio: "oostelijk", // 'westelijk' | 'oostelijk'
    betonning: "PR5",
    diepteNAP_dm: 17,
    diepteALAT_dm: -1,
    alatNapVerschil_dm: 18,
    peildatum: "07-04-2026",
    referentiepunt: "schiermonnikoog",
    zekerheid: "schatting",
    toelichting: "Kust tussen Ameland en Schiermonnikoog — kan ook bij Ameland horen.",
    spring: { hwALAT_dm: 29, verval_dm: 26 },
    dood: { hwALAT_dm: 26, verval_dm: 19 },
  },
  {
    id: "pieterburenwad",
    naam: "Pieterburenwad",
    regio: "oostelijk", // 'westelijk' | 'oostelijk'
    betonning: "Geen betond vaarwater",
    diepteNAP_dm: 3,
    diepteALAT_dm: -14,
    alatNapVerschil_dm: 17,
    peildatum: "03-04-2023",
    referentiepunt: "lauwersoog",
    zekerheid: "schatting",
    toelichting: "Groninger kust, richting Lauwersoog.",
    spring: { hwALAT_dm: 28, verval_dm: 25 },
    dood: { hwALAT_dm: 25, verval_dm: 19 },
  },
  {
    id: "pinkegat",
    naam: "Pinkegat",
    regio: "oostelijk", // 'westelijk' | 'oostelijk'
    betonning: "PG6",
    diepteNAP_dm: 14,
    diepteALAT_dm: -3,
    alatNapVerschil_dm: 17,
    peildatum: "30-03-2026",
    referentiepunt: "ameland",
    zekerheid: "zeker",
    toelichting: "Doc: Ameland (Pinkegat/Holwerderbalg).",
    spring: { hwALAT_dm: 30, verval_dm: 28 },
    dood: { hwALAT_dm: 26, verval_dm: 19 },
  },
  {
    id: "ra-eemswadje",
    naam: "Ra (Eemswadje)",
    regio: "oostelijk", // 'westelijk' | 'oostelijk'
    betonning: "R2",
    diepteNAP_dm: 9,
    diepteALAT_dm: -10,
    alatNapVerschil_dm: 19,
    peildatum: "20-04-2026",
    referentiepunt: null,
    zekerheid: "ontbreekt",
    toelichting: "Bij de Eems; er is nog geen RWS-referentiepunt voor dit gebied in de site.",
    spring: { hwALAT_dm: 30, verval_dm: 27 },
    dood: { hwALAT_dm: 27, verval_dm: 21 },
  },
  {
    id: "reegeul-ameland-t-m-jachthaven",
    naam: "Reegeul Ameland t/m jachthaven",
    regio: "oostelijk", // 'westelijk' | 'oostelijk'
    betonning: "R17 tot R19",
    diepteNAP_dm: 22,
    diepteALAT_dm: 5,
    alatNapVerschil_dm: 17,
    peildatum: "11-11-2025",
    referentiepunt: "ameland",
    zekerheid: "zeker",
    toelichting: "Naam verwijst direct naar Ameland.",
    spring: { hwALAT_dm: 25, verval_dm: 21 },
    dood: { hwALAT_dm: 22, verval_dm: 15 },
  },
  {
    id: "riepel",
    naam: "Riepel",
    regio: "westelijk", // 'westelijk' | 'oostelijk'
    betonning: "R4 <--> R6",
    diepteNAP_dm: 11,
    diepteALAT_dm: -4,
    alatNapVerschil_dm: 15,
    peildatum: "02-03-2026",
    referentiepunt: "terschelling",
    zekerheid: "schatting",
    toelichting: "Bij West-Terschelling.",
    spring: { hwALAT_dm: 25, verval_dm: 21 },
    dood: { hwALAT_dm: 22, verval_dm: 15 },
  },
  {
    id: "scheurrak-omdraai",
    naam: "Scheurrak/Omdraai",
    regio: "westelijk", // 'westelijk' | 'oostelijk'
    betonning: "SO40 <--> SO42 rand vaarwater",
    diepteNAP_dm: 20,
    diepteALAT_dm: 7,
    alatNapVerschil_dm: 13,
    peildatum: "17-02-2026",
    referentiepunt: "texel",
    zekerheid: "zeker",
    toelichting: "Komt overeen met bestaande route via Scheurrak; doc noemt Omdraai bij Texel.",
    spring: { hwALAT_dm: 23, verval_dm: 19 },
    dood: { hwALAT_dm: 20, verval_dm: 16 },
  },
  {
    id: "schuitengat",
    naam: "Schuitengat",
    regio: "westelijk", // 'westelijk' | 'oostelijk'
    betonning: "SG3 <--> SG5",
    diepteNAP_dm: 36,
    diepteALAT_dm: 21,
    alatNapVerschil_dm: 15,
    peildatum: "15-07-2026",
    referentiepunt: "terschelling",
    zekerheid: "zeker",
    toelichting: "Komt direct overeen met bestaande routes via Schuitengat.",
    spring: { hwALAT_dm: 24, verval_dm: 21 },
    dood: { hwALAT_dm: 21, verval_dm: 15 },
  },
  {
    id: "reegeul-schiermonnikoog",
    naam: "Reegeul Schiermonnikoog",
    regio: "oostelijk", // 'westelijk' | 'oostelijk'
    betonning: "R30",
    diepteNAP_dm: 5,
    diepteALAT_dm: -12,
    alatNapVerschil_dm: 17,
    peildatum: "20-04-2026",
    referentiepunt: "schiermonnikoog",
    zekerheid: "zeker",
    toelichting: "Naam verwijst direct naar Schiermonnikoog.",
    spring: { hwALAT_dm: 28, verval_dm: 25 },
    dood: { hwALAT_dm: 25, verval_dm: 18 },
  },
  {
    id: "smeriggat",
    naam: "Smeriggat",
    regio: "oostelijk", // 'westelijk' | 'oostelijk'
    betonning: "SG3 <--> SG5",
    diepteNAP_dm: 12,
    diepteALAT_dm: -6,
    alatNapVerschil_dm: 18,
    peildatum: "10-04-2026",
    referentiepunt: "lauwersoog",
    zekerheid: "schatting",
    toelichting: "Bij Lauwersoog.",
    spring: { hwALAT_dm: 29, verval_dm: 26 },
    dood: { hwALAT_dm: 26, verval_dm: 19 },
  },
  {
    id: "spruit-sp1-sp12",
    naam: "Spruit (SP1-SP12)",
    regio: "oostelijk", // 'westelijk' | 'oostelijk'
    betonning: "SP 7 <--> SP 9",
    diepteNAP_dm: 8,
    diepteALAT_dm: -10,
    alatNapVerschil_dm: 18,
    peildatum: "31-03-2026",
    referentiepunt: "lauwersoog",
    zekerheid: "schatting",
    toelichting: "Doc noemt Spruit als laatste barrière richting Eems-Dollard; Lauwersoog is de dichtstbijzijnde referentie.",
    spring: { hwALAT_dm: 29, verval_dm: 25 },
    dood: { hwALAT_dm: 26, verval_dm: 19 },
  },
  {
    id: "spruit-sp12-zol",
    naam: "Spruit (SP12-ZOL)",
    regio: "oostelijk", // 'westelijk' | 'oostelijk'
    betonning: "SP12 <--> ZOL7-SP14",
    diepteNAP_dm: 7,
    diepteALAT_dm: -11,
    alatNapVerschil_dm: 18,
    peildatum: "08-04-2024",
    referentiepunt: "lauwersoog",
    zekerheid: "schatting",
    toelichting: "Zelfde reden als Spruit (SP1-SP12).",
    spring: { hwALAT_dm: 29, verval_dm: 25 },
    dood: { hwALAT_dm: 26, verval_dm: 19 },
  },
  {
    id: "vaarwater-langs-afsluitdijk",
    naam: "Vaarwater langs Afsluitdijk",
    regio: "westelijk", // 'westelijk' | 'oostelijk'
    betonning: "AD5 <--> AD7",
    diepteNAP_dm: 15,
    diepteALAT_dm: 3,
    alatNapVerschil_dm: 12,
    peildatum: "12-02-2026",
    referentiepunt: "kornwerderzand",
    zekerheid: "schatting",
    toelichting: "Bij de Afsluitdijk/Kornwerderzand.",
    spring: { hwALAT_dm: 20, verval_dm: 17 },
    dood: { hwALAT_dm: 18, verval_dm: 13 },
  },
  {
    id: "vaarwater-naar-de-cocksdorp",
    naam: "Vaarwater naar de Cocksdorp",
    regio: "westelijk", // 'westelijk' | 'oostelijk'
    betonning: "VC9 <--> VC11",
    diepteNAP_dm: 16,
    diepteALAT_dm: 4,
    alatNapVerschil_dm: 12,
    peildatum: "11-02-2026",
    referentiepunt: "texel",
    zekerheid: "zeker",
    toelichting: "De Cocksdorp ligt op Texel.",
    spring: { hwALAT_dm: 20, verval_dm: 17 },
    dood: { hwALAT_dm: 18, verval_dm: 14 },
  },
  {
    id: "vaarwater-over-de-bollen",
    naam: "Vaarwater over de Bollen",
    regio: "westelijk", // 'westelijk' | 'oostelijk'
    betonning: "B3 <--> B5",
    diepteNAP_dm: 20,
    diepteALAT_dm: 8,
    alatNapVerschil_dm: 12,
    peildatum: "23-06-2026",
    referentiepunt: "vlieland",
    zekerheid: "schatting",
    toelichting: "Zandbanken bij Vlieland/Terschelling.",
    spring: { hwALAT_dm: 20, verval_dm: 17 },
    dood: { hwALAT_dm: 18, verval_dm: 14 },
  },
  {
    id: "vaarwater-v-d-zwarte-haan",
    naam: "Vaarwater v.d. Zwarte Haan",
    regio: "westelijk", // 'westelijk' | 'oostelijk'
    betonning: "VH22 <--> VH26",
    diepteNAP_dm: 8,
    diepteALAT_dm: -9,
    alatNapVerschil_dm: 17,
    peildatum: "24-03-2026",
    referentiepunt: "harlingen",
    zekerheid: "zeker",
    toelichting: "Doc noemt dit expliciet naast Kimstergat, bij Harlingen.",
    spring: { hwALAT_dm: 26, verval_dm: 23 },
    dood: { hwALAT_dm: 23, verval_dm: 17 },
  },
  {
    id: "verversgat",
    naam: "Verversgat",
    regio: "westelijk", // 'westelijk' | 'oostelijk'
    betonning: "VVG14/15 richting molenrak",
    diepteNAP_dm: 15,
    diepteALAT_dm: 2,
    alatNapVerschil_dm: 13,
    peildatum: "18-02-2026",
    referentiepunt: "texel",
    zekerheid: "schatting",
    toelichting: "Bij het Marsdiep, Texel.",
    spring: { hwALAT_dm: 22, verval_dm: 19 },
    dood: { hwALAT_dm: 20, verval_dm: 16 },
  },
  {
    id: "vingegat",
    naam: "Vingegat",
    regio: "westelijk", // 'westelijk' | 'oostelijk'
    betonning: "V13 <--> V11A-K40 wantij",
    diepteNAP_dm: 0.5,
    diepteALAT_dm: -16.5,
    alatNapVerschil_dm: 17,
    peildatum: "24-03-2026",
    referentiepunt: "harlingen",
    zekerheid: "zeker",
    toelichting: "Doc noemt dit expliciet naast Kimstergat, bij Harlingen.",
    spring: { hwALAT_dm: 26, verval_dm: 23 },
    dood: { hwALAT_dm: 23, verval_dm: 17 },
  },
  {
    id: "vlielanderbalg",
    naam: "Vlielanderbalg",
    regio: "westelijk", // 'westelijk' | 'oostelijk'
    betonning: "VB14 <--> VB16",
    diepteNAP_dm: 6,
    diepteALAT_dm: -9,
    alatNapVerschil_dm: 15,
    peildatum: "02-03-2026",
    referentiepunt: "vlieland",
    zekerheid: "zeker",
    toelichting: "Doc: wantij van Vlieland is de Vlielanderbalg.",
    spring: { hwALAT_dm: 24, verval_dm: 21 },
    dood: { hwALAT_dm: 21, verval_dm: 15 },
  },
  {
    id: "vliesloot",
    naam: "Vliesloot",
    regio: "westelijk", // 'westelijk' | 'oostelijk'
    betonning: "VS32 <--> VS34",
    diepteNAP_dm: 25,
    diepteALAT_dm: 10,
    alatNapVerschil_dm: 15,
    peildatum: "02-03-2026",
    referentiepunt: "vlieland",
    zekerheid: "schatting",
    toelichting: "Bij Vlieland.",
    spring: { hwALAT_dm: 24, verval_dm: 21 },
    dood: { hwALAT_dm: 21, verval_dm: 15 },
  },
  {
    id: "vlieter",
    naam: "Vlieter",
    regio: "westelijk", // 'westelijk' | 'oostelijk'
    betonning: "VL7 <--> AD8-VL9",
    diepteNAP_dm: 21,
    diepteALAT_dm: 9,
    alatNapVerschil_dm: 12,
    peildatum: "28-01-2026",
    referentiepunt: "vlieland",
    zekerheid: "schatting",
    toelichting: "Vaarwater tussen Vlieland/Terschelling en Kornwerderzand.",
    spring: { hwALAT_dm: 20, verval_dm: 17 },
    dood: { hwALAT_dm: 18, verval_dm: 13 },
  },
  {
    id: "wierbalg",
    naam: "Wierbalg",
    regio: "westelijk", // 'westelijk' | 'oostelijk'
    betonning: "W4",
    diepteNAP_dm: 20,
    diepteALAT_dm: 8,
    alatNapVerschil_dm: 12,
    peildatum: "13-01-2026",
    referentiepunt: "texel",
    zekerheid: "schatting",
    toelichting: "Noordoost Texel.",
    spring: { hwALAT_dm: 29, verval_dm: 26 },
    dood: { hwALAT_dm: 26, verval_dm: 19 },
  },
  {
    id: "wierumerwad-van-sg-naar-fw",
    naam: "Wierumerwad (van SG naar FW)",
    regio: "oostelijk", // 'westelijk' | 'oostelijk'
    betonning: "WW7",
    diepteNAP_dm: 5,
    diepteALAT_dm: -13,
    alatNapVerschil_dm: 18,
    peildatum: "07-04-2026",
    referentiepunt: "lauwersoog",
    zekerheid: "schatting",
    toelichting: "Groninger Wad, richting Lauwersoog.",
    spring: { hwALAT_dm: 29, verval_dm: 26 },
    dood: { hwALAT_dm: 26, verval_dm: 19 },
  },
  {
    id: "wierumerwad-van-pr-naar-sg",
    naam: "Wierumerwad (van PR naar SG)",
    regio: "oostelijk", // 'westelijk' | 'oostelijk'
    betonning: "WW21",
    diepteNAP_dm: 6,
    diepteALAT_dm: -12,
    alatNapVerschil_dm: 18,
    peildatum: "07-04-2026",
    referentiepunt: "lauwersoog",
    zekerheid: "schatting",
    toelichting: "Groninger Wad, richting Lauwersoog.",
    spring: { hwALAT_dm: 29, verval_dm: 26 },
    dood: { hwALAT_dm: 26, verval_dm: 19 },
  },
  {
    id: "zuid-oost-lauwers-uithuizerwad",
    naam: "Zuid Oost Lauwers (Uithuizerwad)",
    regio: "oostelijk", // 'westelijk' | 'oostelijk'
    betonning: "ZOL50 <--> ZOL52 Wantij",
    diepteNAP_dm: 4,
    diepteALAT_dm: -15,
    alatNapVerschil_dm: 19,
    peildatum: "02-04-2026",
    referentiepunt: "lauwersoog",
    zekerheid: "zeker",
    toelichting: "Naam bevat ‘Lauwers’.",
    spring: { hwALAT_dm: 30, verval_dm: 27 },
    dood: { hwALAT_dm: 27, verval_dm: 21 },
  },
  {
    id: "zuider-spruit",
    naam: "Zuider Spruit",
    regio: "oostelijk", // 'westelijk' | 'oostelijk'
    betonning: "ZS22 <--> ZS24",
    diepteNAP_dm: 8,
    diepteALAT_dm: -9,
    alatNapVerschil_dm: 17,
    peildatum: "27-05-2026",
    referentiepunt: "lauwersoog",
    zekerheid: "schatting",
    toelichting: "Groninger Wad, richting Lauwersoog.",
    spring: { hwALAT_dm: 29, verval_dm: 26 },
    dood: { hwALAT_dm: 25, verval_dm: 18 },
  },
  {
    id: "zuidoostrak",
    naam: "Zuidoostrak",
    regio: "westelijk", // 'westelijk' | 'oostelijk'
    betonning: "ZR19A <--> ZR21",
    diepteNAP_dm: 10,
    diepteALAT_dm: -3,
    alatNapVerschil_dm: 13,
    peildatum: "18-02-2026",
    referentiepunt: "vlieland",
    zekerheid: "zeker",
    toelichting: "Komt overeen met bestaande route (Inschot/Zuidoostrak) naar Vlieland.",
    spring: { hwALAT_dm: 23, verval_dm: 19 },
    dood: { hwALAT_dm: 21, verval_dm: 16 },
  },
  {
    id: "zuidoostrak-tot-molenrak",
    naam: "Zuidoostrak tot Molenrak",
    regio: "westelijk", // 'westelijk' | 'oostelijk'
    betonning: "ZR19A",
    diepteNAP_dm: 10,
    diepteALAT_dm: -3,
    alatNapVerschil_dm: 13,
    peildatum: "01-02-2024",
    referentiepunt: "vlieland",
    zekerheid: "zeker",
    toelichting: "Zelfde geulnaam als Zuidoostrak.",
    spring: { hwALAT_dm: 22, verval_dm: 19 },
    dood: { hwALAT_dm: 20, verval_dm: 16 },
  },
]

